name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run E2E tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKE: ${{ secrets.GITHUB_TOKEN }}
          # start: "npm run start:ci"
          # wait-on: "http://localhost:8888"
          # # let's see if the Test Runner handles url in the config
          # # https://github.com/cypress-io/cypress/issues/5466
          # config: baseUrl=http://localhost:8888
